// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// DescribeRecycledResourceRequest is request schema for DescribeRecycledResource action
type DescribeRecycledResourceRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值： cn，表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// 返回数据长度，默认为20，最大100。
	Limit *int `required:"false"`

	// 列表起始位置偏移量，默认为0。
	Offset *string `required:"false"`
}

// DescribeRecycledResourceResponse is response schema for DescribeRecycledResource action
type DescribeRecycledResourceResponse struct {
	response.CommonBase

	// 【数组】返回虚拟机对象数组
	Infos []RecycledResourceInfo

	// 返回信息描述
	Message string

	// 返回虚拟机总个数
	TotalCount int
}

// NewDescribeRecycledResourceRequest will create request of DescribeRecycledResource action.
func (c *UCloudStackClient) NewDescribeRecycledResourceRequest() *DescribeRecycledResourceRequest {
	req := &DescribeRecycledResourceRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// DescribeRecycledResource - 查询UCloudStack虚拟机
func (c *UCloudStackClient) DescribeRecycledResource(req *DescribeRecycledResourceRequest) (*DescribeRecycledResourceResponse, error) {
	var err error
	var res DescribeRecycledResourceResponse

	reqCopier := *req

	err = c.Client.InvokeAction("DescribeRecycledResource", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
