// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// TerminateResourceRequest is request schema for TerminateResource action
type TerminateResourceRequest struct {
	request.CommonBase

	// [公共参数] 地域。 枚举值：cn，表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// 虚拟机 ID。输入有效的虚拟机 ID。
	ResourceID *string `required:"true"`
}

// TerminateResourceResponse is response schema for TerminateResource action
type TerminateResourceResponse struct {
	response.CommonBase

	// 返回信息描述。
	Message string
}

// NewTerminateResourceRequest will create request of TerminateResource action.
func (c *UCloudStackClient) NewTerminateResourceRequest() *TerminateResourceRequest {
	req := &TerminateResourceRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// TerminateResource - 删除UCloudStack虚拟机
func (c *UCloudStackClient) TerminateResource(req *TerminateResourceRequest) (*TerminateResourceResponse, error) {
	var err error
	var res TerminateResourceResponse

	reqCopier := *req

	err = c.Client.InvokeAction("TerminateResource", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
